export const levelOne = [
"What does my phone wallpaper tell you about me?",
"Do I seem like more of a creative or analytical type? Explain.",
"ACTION CARD: Give a compliment to the person on your right",
"Based on what you know of me, what job or career path do you think I'd excel in the most?"
"Am I the type of person who enjoys cooking at home, ordering takeout, or dining at restaurants?",
"ACTION CARD: Give a high-five to the person across you."
"Do you think I'm more inclined to save money for the future or spend it on immediate pleasures?",
"Do you think I fall in love easily? Why or why not?",
"ACTION CARD: Ask someone who seems most similar to you share something they are looking forward to.",
"Do you think I've ever checked an ex's phone for evidence?",
"Do you think I've ever had my heart broken?",
"If I were to order a pizza, what toppings do you think I'd choose?",
"Have everyone share where they would they want to go if they could travel anywhere, regardless of the cost.",
"ACTION CARD: Guess the love language of each person in the group based on how they look.",
"What's your guess about my favorite type of music and artist?",
"Have the group share one movie or show they recommend as a must-watch.",
"ACTION CARD: Find something you have in common with the person on your left.",
"Based on how I look, what kind of musical instrument should I play?",
"What is one game you would recommend for people to play?",
"ACTION CARD: Together with two other people in the group make a TikTok/Instagram Reel together. Post and tag the restaurant!",
"What kind of sports do you imagine I'd be most interested in watching?",
"What compliment do you think I hear the most?"
"Do you think I was popular in school? Explain."
"ACTION CARD: Choose two people (1 male and 1 female) to move to the karaoke room to play a total of 3 rounds of Level 3. Resume the game when they come back.",
"What is the worst assumption someone made about you?"
];

export const levelTwo = [
"ACTION CARD: In alphabetical order based on your passport name, share a random act of kindness moment you've either given or received.",
"What do you think is the hardest part of what I do for a living?",
"As a child what do you think I wanted to be?",
"What does my instagram tell you about me?",
"Has a stranger ever changed your life?",
"What are you currently most grateful for and why?",
"Dear younger self: __________",
"ACTION CARD: Choose two people (1 male and 1 female) to move to the karaoke room to play a total of 8 rounds of Level 3 of this game.",
"What's been your happiest memory this past year?",
"Who in your life deserves the biggest thank you? Let them know if you can.",
"What's your favorite part of yourself that isn't physical?",
"What is something you've learned about yourself this week?",
"What's your mother's name and the most valuable lesson she's taught you thus far?",
"ACTION CARD: Get the males to choose to play a total of 18 rounds of Level 3 of this game with a female of their choice. Let the youngest start.",
"Which one of your parent's personality traits do you want to keep/let go of?",
"What are your more afraid of, failure or success? And why?",
"Something that brought a smile to my face this week was ___.",
"What is your most toxic trait that you can admit to?",
"What question did this year leave you with?",
"ACTION CARD: Get the males to choose to play a total of 24 rounds of Level 3 of this game with a female of their choice. Let the oldest start.",
"What have you been taking for granted lately?",
"When was the last time you felt most yourself?",
"Have you ever told someone I love you, but didn't mean it? If so, why?",
"Have you changed your mind about anything recently?",
"What would you never want to change about yourself?",
"ACTION CARD: Get the females to choose to play a total of 24 rounds of Level 3 of this game with a male of their choice. Let the oldest start.",
"Are you lying to yourself about anything?",
"What's your perspective on how you handle setbacks or failures in life, and how resilient do you think you are?",
"If you could have it your way: Who would you be with? Where would you be? And what would you be doing?",
"What was the lesson in your most recent painful experience?",
"If you could get to know someone in your life on a deeper level, who would it be and why?",
"ACTION CARD: Ask each person in the group to share a red flag they look out for. Rate their answer on a scale of 1-10.",
"What is a compliment you wish you received more frequently?",
"What question are you trying to answer most in your life right now?",
"What is the last thing you lied to your mother about?",
"What title would you give this chapter in your life?",
"What do you crave more of?",
"ACTION CARD: Get the females to choose to play a total of 18 rounds of Level 3 of this game with a male of their choice. Let the youngest start.",
"Is there a feeling you miss?",
"What has been your earliest recollection of happiness?",
"What's a relationship deal-breaker for you and why?",
"What belief about yourself no longer serves you?",
"What is the most unexplainable thing that's ever happened to you?",
"ACTION CARD: Get the group to make a TikTok/Instagram Reel of the restaurant. Post and tag the restaurant!",
"What's the hardest lesson you've learned in love?",
"If you could have a dinner with anyone in the world dead or alive, who would it be? ",
"What are you most afraid of?",
"What is something that you can talk about for hours?",
"In order of birth month, take turns to describe what a perfect day in your life would be.",
"ACTION CARD: Split the group into pairs of your choice (1 male and 1 female) and play a total of 12 rounds of Level 3 this game.",
];

export const levelThree = [
  "What can I help you with?",
  "Why do you think we met?",
  "What about me surprised you?",
  "In a word, how would you describe our conversation?",
  "What do you think my strength is?",
  "What can I teach you?",
  "Based on what you've learned about me, do you have any Netflix recommendations?",
  "Who do I remind you of?",
  "What can you be kinder towards yourself for today?",
  "What's one small thing you can do to be a better person in 2019?",
  "What can we create together?",
  "How would you describe me to a stranger?",
  "What about me most surprised you?",
  "What would be the perfect gift for me?",
  "What do you admire most about me?",
  "Based on what you learned about me, what book would you recommend I read?",
  "What about me is hardest for you to understand?",
  "What am I most qualified to give advice about?",
  "What is one thing you think I can do that would dramatically improve my life?",
  "If we were in a band, what would our name be?",
  "Based on what you learned about me, does my social media accurately reflect who I am? Why or why not?",
  "What do I need to hear right now?",
  "Based on what you know about me, do you have any netflix recommendations?",
  "What do you think my superpower is?",
  "What is a lesson you will take away from our conversation?",
  "When in this game did you feel most connected to me?",
  "How does one earn your vulnerability? Have I earned it? How can I earn more?",
  "What do you think our most important similarity is?",
  "In one word, how would you describe our conversation?",
  "What answer of mine made you light up?",
  "When this game is over, what will you remember about me?",
  "What question were you most afraid to answer?",
  "What parts of yourself do you see in me?",
  "How do our personalities complement each other?",
  "What do you think my weakness is?",
  "What would make you feel closer to me?",
  "What do you think I fear the most?",
  "What has this conversation taught you about yourself?",
  "What do you think I should know about myself that perhaps I'm unaware of?",
  "What do you think my defining characterisitic is?",
  "Do you believe everyone has a calling? If so, do you think I've found mine?",
  "What do you recommend I let go of, if anything?",
  "In one word, describe how you feel right now",
];

export const finalLevel = [
  "This is your final level card",
]
